# Generated by Django 4.2.3 on 2023-10-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_auto_20230729_0856'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishingredient',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(through='product.DishIngredient', to='product.ingredient', verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование блюда'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена в рублях за единицу'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='glossary.measurementunit', verbose_name='Единица измерения'),
        ),
    ]
