# Generated by Django 4.2.3 on 2023-12-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_quantity_dishingredient_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ingredient'),
        ),
    ]
