# Generated by Django 4.2.3 on 2023-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Наименоване', max_length=50)),
                ('designation', models.CharField(help_text='Обозначение', max_length=10)),
            ],
        ),
    ]
