# Generated by Django 4.2.3 on 2023-07-29 08:56

from django.db import migrations

from glossary.models import MEASUREMENT_UNITS


def fill_measurements(apps, schema_editor):
    MeasurementUnit = apps.get_model('glossary', 'MeasurementUnit')
    MeasurementUnit.objects.bulk_create(
        [
            MeasurementUnit(full_name=name, designation=designation) for name, designation in MEASUREMENT_UNITS
        ]

    )
    # for name, designation in MEASUREMENT_UNITS:



class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_measurements),
    ]
